### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by asdfok** [MrJmpl3/nodejs--console-social-scraper-downloader-organizer#3]
C:\Windows\System32\node_modules\social-scraper-downloader-organizer>yarn run build
asset facebookMobile.bundle.js 670 bytes [emitted] (name: facebookMobile)
asset instagram.bundle.js 670 bytes [emitted] (name: instagram)
asset tiktok.bundle.js 670 bytes [emitted] (name: tiktok)

ERROR in facebookMobile
Module not found: Error: Recursion in resolving
Stack:
  undefined: (C:\Windows\System32\node_modules\social-scraper-downloader-organizer) .//src/facebookMobile.ts

ERROR in instagram
Module not found: Error: Recursion in resolving
Stack:
  undefined: (C:\Windows\System32\node_modules\social-scraper-downloader-organizer) ./src/instagram.ts

ERROR in tiktok
Module not found: Error: Recursion in resolving
Stack:
  undefined: (C:\Windows\System32\node_modules\social-scraper-downloader-organizer) ./src/tiktok.ts

webpack 5.24.2 compiled with 3 errors in 62 ms

how to fix this?

**Comment by MrJmpl3** [comment]
What is the version of yarn, nodejs?

**Comment by r1bnc** [comment]
I have no error when building but the error is at the program execution of facebookMobile scraping:

`~/nodejs--console-social-scraper-downloader-organizer$ yarn run facebookMobile https://facebook.com/username  --dev
/home/user/nodejs--console-social-scraper-downloader-organizer/node_modules/stdout-update/lib/Wrapper.js:57
    while (last > 0 && string_width_1.default(words[last - 1] ?? '') <= 0)
                                                               ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/user/nodejs--console-social-scraper-downloader-organizer/node_modules/stdout-update/lib/UpdateManager.js:20:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)`

**Comment by MrJmpl3** [comment]
I upgrade the code, please respond if you still have problem

**Comment by r1bnc** [comment]
Ok, this error:

```
$ yarn run facebook https://facebook.com/-------
✔ Login
✖ Download profile https://facebook.com/------
  › waiting for selector `.timeline.albums` failed: timeout 30000ms exceeded

```
facebookMobile script is not found so I used yarn run facebook.

**Comment by MrJmpl3** [comment]
> 
> 
> Ok, `git pull`, `yarn run build`, when running `yarn run facebook <urlusernamefb>` this error:
> 
> ```
> $ yarn run facebook https://facebook.com/-------
> ✔ Login
> ✖ Download profile https://facebook.com/------
>   › waiting for selector `.timeline.albums` failed: timeout 30000ms exceeded
> ```
> 
> facebookMobile script is not found so I used yarn run facebook.
> Will do some tests later, but I won't be available for 9 hours since publication of this comment.
> Thank You

Ok, Facebook Mobile and Facebook Desktop are merge in only Facebook (Mobile to scraping and Desktop to get the images with good resolution)

The scraping work for the moments to profiles and not with pages (I will make work with pages soon)

I add more timeout, please try again

**Comment by r1bnc** [comment]
I was trying it with a profile, I haven't tried with pages. Thank you I will retry again.

**Comment by r1bnc** [comment]
Still error on timeout, does it work for you?

I just used: ` yarn run facebook https://facebook.com/<profileusername>`
The target is a normal profile not a page.

**Comment by r1bnc** [comment]
```
X Download profile ....
 › waiting for selector `.timeline.albums` failed: timeout 120000ms exceeded
```

**Comment by MrJmpl3** [comment]
> 
> 
> ```
> X Download profile ....
>  › waiting for selector `.timeline.albums` failed: timeout 120000ms exceeded
> ```

Check the `www` before of facebook.com

`https://www.facebook.com/<profileusername>`

Another question? The account is a name or with `profile.php?id=`?

**Comment by r1bnc** [comment]
I tried both `profile.php?id=` and `fb.com/username`

**Comment by MrJmpl3** [comment]
> 
> 
> I tried both `profile.php?id=` and `fb.com/username`

Ok, the scraper dont work with `https://www.facebook.com/profile.php?id=` and `fb.com/username`, only work with `https://www.facebook.com/<profileusername>`

For example my Facebook: https://www.facebook.com/josemanuel.casaniguerra

**Comment by r1bnc** [comment]
Will do more tests tomorrow. But I remember I tried the same format as your username.

but I encountered the timeout error.

**Comment by r1bnc** [comment]
Ok, I tested the latest master branch and it still timesout.
1.  Navigation timeout of 30000 ms exceeded
2. › waiting for selector `.timeline.albums` failed: timeout 120000ms exceeded
BTW, the script redirects ` https://www.facebook.com/josemanuel.casaniguerra`
to  `Download profile https://m.facebook.com/josemanuel.casaniguerra`
then times out again.

Fyi

**Comment by r1bnc** [comment]
full output: 
```
$ yarn run facebook  https://www.facebook.com/josemanuel.casaniguerra
✖ Login
  › Navigation timeout of 30000 ms exceeded
✖ Download profile https://m.facebook.com/josemanuel.casaniguerra
  › waiting for selector `.timeline.albums` failed: timeout 120000ms exceeded

```

**Comment by MrJmpl3** [comment]
> 
> 
> full output:
> 
> ```
> $ yarn run facebook  https://www.facebook.com/josemanuel.casaniguerra
> ✖ Login
>   › Navigation timeout of 30000 ms exceeded
> ✖ Download profile https://m.facebook.com/josemanuel.casaniguerra
>   › waiting for selector `.timeline.albums` failed: timeout 120000ms exceeded
> ```

mmm, that is strange, your Facebook is in English? Can you check if your user and password are correct?

**Comment by r1bnc** [comment]
It is in English, how do I know if the password are incorrect or not being accepted, pretty sure they are correct.

**Comment by MrJmpl3** [comment]
> It is in English, how do I know if the password are incorrect or not being accepted, pretty sure they are correct.

Use the argument `--dev`, the dev argument show the internal browser of the scraper

**Comment by r1bnc** [comment]
I used the `--dev` and noticed the chrome fb is not on English.  (IP address location)
Issue appears to be my fault.
It works now, feel free to close this.

**Comment by r1bnc** [comment]
Ok, would the process resume when the internet connection is lost?

**Comment by r1bnc** [comment]
Also, kindly clarify on the README on what data are saved.

Thank you

**Comment by MrJmpl3** [comment]
> Ok, would the process resume when the internet connection is lost?

For the moment, no, I will add this in future versions
